name: Deploy project to AWS EC2

on:
  push:
    branches: [ main ]   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r ./ ubuntu@ec2-52-64-16-48.ap-southeast-2.compute.amazonaws.com:/var/www/html/docAppoint

    - name: Restart Apache on EC2
      run: |
        ssh ubuntu@ec2-52-64-16-48.ap-southeast-2.compute.amazonaws.com "sudo systemctl restart apache2"
